version: "3"
volumes:
  docker:

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - docker:/data/db

  next:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://mongodb:27017/next-docker
      NODE_ENV: 'production'
    depends_on:
      - mongodb